import pygame, sys
import random
from enum import Enum

TILE_SIZE = 32
SCREEN_HEIGHT = TILE_SIZE * 20
SCREEN_WIDTH = TILE_SIZE * 40


class MazeCellType(Enum):
    WALL = 1
    FRUIT = 2
    EMPTY = 3
    POINT = 4


class Maze:
    def __init__(self) -> None:
        self.cells: list[list[MazeCellType]] = [
            [
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.POINT,
                MazeCellType.WALL,
            ],
            [
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
                MazeCellType.WALL,
            ],
        ]

    def draw(self, screen):
        for ic, row in enumerate(self.cells):
            for ir, c in enumerate(row):
                if c == MazeCellType.POINT:
                    pygame.draw.circle(
                        screen,
                        (255, 165, 0),
                        (
                            ir * TILE_SIZE + TILE_SIZE / 2,
                            ic * TILE_SIZE + TILE_SIZE / 2,
                        ),
                        5,
                    )
                if c == MazeCellType.WALL:
                    pygame.draw.rect(
                        screen,
                        (255, 0, 255),
                        (ir * TILE_SIZE, ic * TILE_SIZE, TILE_SIZE, TILE_SIZE),
                        5,
                    )


class Pacman:
    def __init__(self) -> None:
        self.images = {
            pygame.K_RIGHT: [
                pygame.image.load("pacman/images/pacman/pacman_right_0.png"),
                pygame.image.load("pacman/images/pacman/pacman_right_1.png"),
            ],
            pygame.K_LEFT: [
                pygame.image.load("pacman/images/pacman/pacman_left_0.png"),
                pygame.image.load("pacman/images/pacman/pacman_left_1.png"),
            ],
            pygame.K_DOWN: [
                pygame.image.load("pacman/images/pacman/pacman_down_0.png"),
                pygame.image.load("pacman/images/pacman/pacman_down_1.png"),
            ],
            pygame.K_UP: [
                pygame.image.load("pacman/images/pacman/pacman_up_0.png"),
                pygame.image.load("pacman/images/pacman/pacman_up_1.png"),
            ],
        }
        self.x = 64
        self.y = 64
        self.image_number = 0
        self.timer = pygame.time.get_ticks()
        self.direction = None

    def process_keys(self, keys):
        if self.direction == pygame.K_LEFT or keys[pygame.K_LEFT]:
            if (
                self.x % TILE_SIZE == 0 and self.y % TILE_SIZE == 0
            ) or self.direction == pygame.K_LEFT:
                self.direction = pygame.K_LEFT
                self.x -= 0.25
                if self.timer + 200 < pygame.time.get_ticks():
                    self.image_number = 1 if self.image_number == 0 else 0
                    self.timer = pygame.time.get_ticks()
        if self.direction == pygame.K_RIGHT or keys[pygame.K_RIGHT]:
            if (
                self.x % TILE_SIZE == 0 and self.y % TILE_SIZE == 0
            ) or self.direction == pygame.K_RIGHT:
                self.direction = pygame.K_RIGHT
                self.x += 0.25
                if self.timer + 200 < pygame.time.get_ticks():
                    self.image_number = 1 if self.image_number == 0 else 0
                    self.timer = pygame.time.get_ticks()
        if self.direction == pygame.K_UP or keys[pygame.K_UP]:
            if (
                self.x % TILE_SIZE == 0 and self.y % TILE_SIZE == 0
            ) or self.direction == pygame.K_UP:
                self.direction = pygame.K_UP
                self.y -= 0.25
                if self.timer + 200 < pygame.time.get_ticks():
                    self.image_number = 1 if self.image_number == 0 else 0
                    self.timer = pygame.time.get_ticks()
        if self.direction == pygame.K_DOWN or keys[pygame.K_DOWN]:
            if (
                self.x % TILE_SIZE == 0 and self.y % TILE_SIZE == 0
            ) or self.direction == pygame.K_DOWN:
                self.direction = pygame.K_DOWN
                self.y += 0.25
                if self.timer + 200 < pygame.time.get_ticks():
                    self.image_number = 1 if self.image_number == 0 else 0
                    self.timer = pygame.time.get_ticks()

    def draw(self, screen):
        if self.direction != None:
            screen.blit(
                self.images[self.direction][self.image_number], (self.x, self.y)
            )
        else:
            screen.blit(self.images[pygame.K_RIGHT][0], (self.x, self.y))


pygame.init()
screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
pygame.display.set_caption("Pacman")
pacman = Pacman()
maze = Maze()
while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()
    screen.fill((0, 0, 0))
    # for i in range(0, SCREEN_WIDTH // TILE_SIZE):
    #     for j in range(0, SCREEN_HEIGHT // TILE_SIZE):
    #         pygame.draw.rect(
    #             screen,
    #             (255, 255, 255),
    #             (i * TILE_SIZE, j * TILE_SIZE, TILE_SIZE, TILE_SIZE),
    #             1,
    #         )
    pacman.process_keys(pygame.key.get_pressed())
    maze.draw(screen)
    pacman.draw(screen)

    pygame.display.flip()
